package main

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
)

// ExcelFiles is a slice of Excel file paths.
type Files []string

// excelExtensions is a case-insensitive regexp matching the list of legitimate Excel
// filename extensions to be considered by this program. See
// https://en.wikipedia.org/wiki/List_of_Microsoft_Office_filename_extensions for more
// information. This extension matcher is given the output of `filepath.Ext`, which
// includes the leading period or `.`.
//
// Note that macro and template types are presently excluded, namely:
// .xlsm – Excel macro-enabled workbook; same as xlsx but may contain macros and scripts
// .xltx – Excel template
// .xltm – Excel macro-enabled template; same as xltx but may contain macros and scripts
var regexpExcelExtensions *regexp.Regexp = regexp.MustCompile(`(?i)^\.(xlsx|xls)`)

// ParseFileList takes a list of prospective files and/or directories and parses them
// into valid excel files. In thi context, "valid" Excel files are actual files on disk
// with the expected Excel file extensions.
//
// All inputs are expected to be either a path to an Excel file or a directory
// containing (at the top level) one or more Excel files, potentially amongst other file
// types. It is an error to provide a path to a file which is not an Excel file.
//
// Note that the golang Excelize module used elsewhere in this program supports
// "Supports reading and writing spreadsheet documents generated by Microsoft Excel™
// 2007 and later". See https://github.com/qax-os/excelize for more info.
func ParseFileList(paths ...string) (*Files, error) {

	if len(paths) == 0 {
		return nil, errors.New("no files provided")
	}

	files := Files{}

	// processDir looks for Excel files in a directory and adds relevant files to the
	// file list.
	processDir := func(dirPath string) error {
		var count int
		dirContents, err := os.ReadDir(dirPath)
		if err != nil {
			return fmt.Errorf("could not read dir %q: %v", dirPath, err)
		}
		for _, dc := range dirContents {
			if dc.IsDir() {
				continue
			}
			name := dc.Name()
			if !regexpExcelExtensions.MatchString(filepath.Ext(name)) {
				continue
			}
			count++
			files = append(files, filepath.Join(dirPath, name))
		}
		if count == 0 {
			return fmt.Errorf("directory %q had no valid Excel files", dirPath)
		}
		return nil
	}

	for _, p := range paths {
		isDirectory, err := isDirectory(p)
		if err != nil {
			return nil, err
		}
		if isDirectory {
			err := processDir(p)
			if err != nil {
				return nil, err
			}
			continue
		}
		// If not a directory, check if the file matches the extension regexp. If it
		// doesn't, raise an error.
		if !regexpExcelExtensions.MatchString(filepath.Ext(p)) {
			return nil, fmt.Errorf("file %q does not have a valid Excel file extension", p)
		}
		files = append(files, p)
	}
	return &files, nil
}

// isDirectory checks if a path exists and if it does, if it is a directory.
func isDirectory(path string) (bool, error) {
	s, err := os.Stat(path)
	if err != nil {
		return false, fmt.Errorf("could not stat path %q: %w", path, err)
	}
	return s.IsDir(), nil
}
